# Generated by Django 2.1.15 on 2019-12-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genetic', '0002_auto_20150831_1258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gene',
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
        migrations.DeleteModel(
            name='Technique',
        ),
    ]
