# Generated by Django 2.1.10 on 2019-09-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_auto_20181220_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ethically_cleared',
            field=models.BooleanField(default=False),
        ),
    ]
