# Generated by Django 2.2.9 on 2020-01-21 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_customuser_ethically_cleared'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
