# Generated by Django 2.2.10 on 2020-05-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_unset_staff_status_for_patient_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='force_password_reset',
            field=models.BooleanField(default=False, help_text='Force this user to reset their password to access the system.', verbose_name='force password reset'),
        ),
    ]
