# Generated by Django 2.2.24 on 2021-09-06 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_customuser_force_password_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates that this user has elevated patient management permissions.', verbose_name='staff status'),
        ),
    ]
