# Generated by Django 2.2.10 on 2020-05-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_customuser_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='untrusted_source_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='untrusted_sources_lockout_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
