# Generated by Django 3.2.16 on 2023-02-01 09:55

from django.db import migrations
import registry.groups.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_staff_help_text'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', registry.groups.models.CustomUserManager()),
            ],
        ),
    ]
