# Generated by Django 3.2.18 on 2023-03-17 14:49

from django.db import migrations
from django.db.models.functions import Lower

from registry.groups import GROUPS as RDRF_GROUPS


def _report_groups(apps):
    Group = apps.get_model('auth', 'Group')
    return Group.objects.annotate(name_lower=Lower('name')).\
        filter(name_lower__in=[RDRF_GROUPS.WORKING_GROUP_STAFF, RDRF_GROUPS.WORKING_GROUP_CURATOR, RDRF_GROUPS.CLINICAL])


def _content_type(apps):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ReportDesign = apps.get_model('report', 'ReportDesign')

    return ContentType.objects.get_for_model(ReportDesign)

def _can_run_report_permission(apps):
    Permission = apps.get_model('auth', 'Permission')

    return Permission.objects.get(codename='can_run_reports', content_type=_content_type(apps))


def insert_report_permission(apps, schema_editor):
    Permission = apps.get_model('auth', 'Permission')

    Permission.objects.create(codename='can_run_reports',
                              name='Can run reports',
                              content_type=_content_type(apps))


def delete_report_permission(apps, schema_editor):
    can_run_report = _can_run_report_permission(apps)
    can_run_report.delete()


def grant_report_permission_to_groups(apps, schema_editor):
    can_run_report = _can_run_report_permission(apps)

    for group in _report_groups(apps):
        group.permissions.add(can_run_report)


def revoke_report_permission(apps, schema_editor):
    can_run_report = _can_run_report_permission(apps)

    for group in _report_groups(apps):
        group.permissions.remove(can_run_report)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0018_alter_customuser_managers'),
        ('report', '0003_reportdesign_cde_include_form_timestamp'),
    ]

    operations = [
        migrations.RunPython(insert_report_permission, delete_report_permission),
        migrations.RunPython(grant_report_permission_to_groups, revoke_report_permission),
    ]
