# Generated by Django 3.2.18 on 2023-05-05 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_alter_workinggroup_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEmailChangeRequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('current_username', models.CharField(max_length=254)),
                ('current_user_email', models.EmailField(max_length=254, verbose_name='current email address')),
                ('current_patient_email', models.EmailField(max_length=254, null=True, verbose_name='current email address')),
                ('new_email', models.EmailField(max_length=254, verbose_name='new email address')),
                ('request_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=80)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical email change request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_username', models.CharField(max_length=254)),
                ('current_user_email', models.EmailField(max_length=254, verbose_name='current email address')),
                ('current_patient_email', models.EmailField(max_length=254, null=True, verbose_name='current email address')),
                ('new_email', models.EmailField(max_length=254, verbose_name='new email address')),
                ('request_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
