# Generated by Django 3.2.18 on 2023-05-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0155_label_lf_email'),
        ('groups', '0020_alter_workinggroup_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workinggroup',
            unique_together={('registry', 'name')},
        ),
    ]
