# Generated by Django 3.2.18 on 2023-05-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_emailchangerequest_historicalemailchangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinggroup',
            options={'ordering': ['registry__code', 'type__name', 'name']},
        ),
    ]
