# Generated by Django 3.2.20 on 2023-10-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0023_alter_workinggroup_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_activated',
            field=models.DateTimeField(null=True, verbose_name='date activated'),
        ),
    ]
