# Generated by Django 5.2.1 on 2026-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_alter_workinggrouptype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalemailchangerequest',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical email change request', 'verbose_name_plural': 'historical email change requests'},
        ),
        migrations.AlterField(
            model_name='historicalemailchangerequest',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
