# Generated by Django 2.2.28 on 2022-05-06 13:17
import logging

import django.db.models.deletion
from django.db import migrations, models

logger = logging.getLogger(__name__)

from rdrf.helpers.utils import get_form_section_code


def set_default_cfg_for_clinicaldatafield(apps, schema_editor):
    ReportClinicalDataField = apps.get_model('report', 'ReportClinicalDataField')
    ReportDesign = apps.get_model('report', 'ReportDesign')
    ContextFormGroupItem = apps.get_model('rdrf', 'ContextFormGroupItem')

    for cde_field in ReportClinicalDataField.objects.all():
        logger.info(f'Setting CFG for cde_field {cde_field.id}')
        report_design = ReportDesign.objects.get(id=cde_field.report_design_id)
        form_name, section_code, cde_code = get_form_section_code(cde_field.cde_key)

        first_matching_cfg_item = ContextFormGroupItem.objects.get(registry_form__name=form_name,
                                                                   context_form_group__registry__id=report_design.registry_id)

        logger.info(f'Setting to first matching CFG with id {first_matching_cfg_item.context_form_group.id}')
        cde_field.context_form_group = first_matching_cfg_item.context_form_group
        cde_field.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0140_add_abbreviated_name_fields'),
        ('report', '0001_initial'),
    ]


    operations = [
        migrations.AddField(
            model_name='reportclinicaldatafield',
            name='context_form_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.ContextFormGroup'),
        ),
        migrations.RunPython(
            set_default_cfg_for_clinicaldatafield,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='reportclinicaldatafield',
            name='context_form_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.ContextFormGroup'),
        )
    ]
