version: '2'
services:

  datatest:
    extends:
      file: docker-compose-common.yml
      service: datatest

  dbtest:
    extends:
      file: docker-compose-common.yml
      service: db

  dbclinicaltest:
    extends:
      file: docker-compose-common.yml
      service: db

  dbfdptest:
    extends:
      file: docker-compose-common.yml
      service: dbfdp

  cachetest:
    extends:
      file: docker-compose-common.yml
      service: cache

  mongotest:
    extends:
      file: docker-compose-common.yml
      service: mongo

  runservertest:
    extends:
      file: docker-compose-common.yml
      service: runserver
    volumes_from:
      - datatest
    command: runserver
    environment:
      - DJANGO_FIXTURES=test
      - ALLOWED_HOSTS=*
      - CACHESERVER=cachetest
      - DBSERVER=dbtest
      - CLINICAL_DBSERVER=dbclinicaltest
      - MONGOSERVER=mongotest
    depends_on:
      - dbtest
      - dbclinicaltest
      - dbfdptest
      - cachetest
      - mongotest
    ports:
      - "18000:8000"
