version: "3.7"

volumes:
  db_data:
  clinicaldb_data:
  reportingdb_data:

services:
  db:
    image: postgres:10.7
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  clinicaldb:
    image: postgres:10.7
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - clinicaldb_data:/var/lib/postgresql/data
    expose:
      - "5432"

  reportingdb:
    image: postgres:10.7
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - reportingdb_data:/var/lib/postgresql/data
    expose:
      - "5432"

  application:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: trrf-application
    restart: always
    command: uwsgi_ssl
    environment:
      - LOGIN_PAGE_MESSAGE=This is a demo instance. No personal or private data should be entered
      - TIME_ZONE
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DBUSER=${POSTGRES_USER}
      - DBPASS=${POSTGRES_PASSWORD}
    env_file:
      - docker/production/envs/prod-local-db
      - docker/production/envs/uwsgi
    ports:
      - 443:9443
    volumes:
      - ./data/prod/:/data
    depends_on:
      - db
      - clinicaldb
      - reportingdb
