#
dataselenium:
  extends:
    file: docker-compose-seleniumstack.yml
    service: dataselenium

# runs the selenium tests against the stack above
seleniumtesthost:
  image: angelman_runserverselenium
  command: selenium
  environment:
    - DJANGO_SETTINGS_MODULE=rdrf.settings
    - DBUSER=rdrfapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_RUNSERVER=1
    - WAIT_FOR_MONGO=1
  volumes_from:
    - dataselenium      
  external_links:
    - angelman_dbselenium_1:db
    - angelman_runserverselenium_1:web
    - angelman_mongoselenium_1:mongo
    - angelman_seleniumhub_1:hub
    - angelman_reportingselenium_1:reporting
