version: '2'
services:

  datadev:
    extends:
      file: docker-compose-common.yml
      service: datadev

  jasper:
    extends:
      file: docker-compose-common.yml
      service: jasper
    depends_on:
      - db

  db:
    extends:
      file: docker-compose-common.yml
      service: db

  cache:
    extends:
      file: docker-compose-common.yml
      service: cache

  mongo:
    extends:
      file: docker-compose-common.yml
      service: mongo

  nginx:
    extends:
      file: docker-compose-common.yml
      service: nginx
    depends_on:
      - uwsgi

  runserver:
    extends:
      file: docker-compose-common.yml
      service: runserver
    volumes_from:
      - datadev
    depends_on:
      - db
      - cache
      - mongo
      - jasper
    ports:
      - "8000:8000"
  uwsgi:
    extends:
      file: docker-compose-common.yml
      service: uwsgi
    volumes_from:
      - datadev
    depends_on:
      - db
      - cache
      - mongo
      - runserver
      - jasper
