version: '3.7'

x-common-env-variables: &common-env-variables
  DEBUG: 0
  TEST_WAIT: 10
  TEST_BROWSER: chrome
  ALLOWED_HOSTS: '*'

  TEST_APP_HOST: serverundertest

  DBSERVER: dbtest
  CLINICAL_DBSERVER: dbclinicaltest
  REPORTING_DBSERVER: dbreportingtest
  CACHESERVER: cachetest
  CONSOLE_LOG_LEVEL: WARNING

  AWS_XRAY_SDK_ENABLED: 0


services:
  aloe_dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: ${TRRF_IMAGE_NAME}
    command: aloe
    environment:
      <<: *common-env-variables
      WAIT_FOR_RUNSERVER: 1
      RUNSERVER: serverundertest
      TRRF_SITE_DOMAIN: 'serverundertest:8000'
      TRRF_SITE_NAME: 'TRRF-Aloe'
    volumes:
      - .:/app
      - ./data/aloe/dev:/data

  aloe_prod:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile
    image: ${TRRF_IMAGE_NAME}
    command: aloe
    environment:
      <<: *common-env-variables
      WAIT_FOR_UWSGI: 1
      UWSGISERVER: serverundertest
      TEST_APP_PORT: 9000
    volumes:
      - .:/app
      - ./data/aloe/prod:/data
