version: '3.7'

services:
  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "18123:8123"
      - "19000:9000"
    volumes:
      - "./clickhouse-server:/etc/clickhouse-server/"
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    expose:
      - "18123"