#
dataselenium:
  image: muccg/debian8-base
  volumes:
    - .:/app
    - ./data/selenium:/data

seleniumhub:
  image: selenium/hub
  ports:
    - "4444"

chrome:
  image: selenium/node-chrome
  links:
  - seleniumhub:hub
  - runserverselenium:web

firefox:
  image: selenium/node-firefox
  links:
  - seleniumhub:hub
  - runserverselenium:web

smtpselenium:
  extends:
    file: docker-compose-common.yml
    service: smtp

dbselenium:
  extends:
    file: docker-compose-common.yml
    service: db

reportingselenium:
  extends:
    file: docker-compose-common.yml
    service: reporting

cacheselenium:
  extends:
    file: docker-compose-common.yml
    service: cache

mongoselenium:
  extends:
    file: docker-compose-common.yml
    service: mongo

runserverselenium:
  build: .
  command: runserver
  environment:
    - DJANGO_SETTINGS_MODULE=rdrf.settings
    - DBUSER=rdrfapp
    - WAIT_FOR_DB=1
    - WAIT_FOR_CACHE=1
    - WAIT_FOR_MONGO=1
  volumes_from:
    - dataselenium      
  ports:
    - "8000"
  links:
    - dbselenium:db
    - cacheselenium:cache
    - mongoselenium:mongo
    - smtpselenium:smtp
