version: "3.7"

volumes:
  db_data:
  clinicaldb_data:
  reportingdb_data:

services:
  db:
    image: postgres:10.7
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  clinicaldb:
    image: postgres:10.7
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - clinicaldb_data:/var/lib/postgresql/data
    expose:
      - "5432"

  reportingdb:
    image: postgres:10.7
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - reportingdb_data:/var/lib/postgresql/data
    expose:
      - "5432"

  application:
    build:
      context: .
      dockerfile: docker/production/Dockerfile
    image: trrf-backend
    command: uwsgi_ssl
    environment: 
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - DBUSER=${POSTGRES_USER}
      - DBPASS=${POSTGRES_PASSWORD}
    env_file:
      - docker/dev/envs/runserver
      - docker/production/envs/uwsgi
    ports:
      - 443:9443
    volumes:
      - ./data/prod/:/data
    depends_on:
      - db
      - clinicaldb
      - reportingdb
