datatest:
  extends:
    file: docker-compose-common.yml
    service: datatest

dbtest:
  extends:
    file: docker-compose-common.yml
    service: db

fdp_dbtest:
  extends:
    file: docker-compose-common.yml
    service: fdp_db

cachetest:
  extends:
    file: docker-compose-common.yml
    service: cache

mongotest:
  extends:
    file: docker-compose-common.yml
    service: mongo

runservertest:
  extends:
    file: docker-compose-common.yml
    service: runserver
  volumes_from:
    - datatest
  command: runserver
  environment:
    - DEPLOYMENT=test
    - ALLOWED_HOSTS=*
  links:
    - dbtest:db
    - fdp_dbtest:fdp_db
    - cachetest:cache
    - mongotest:mongo
  ports:
    - "18000:8000"
