[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "trrf"
version = "1.0.0"
description = "Trial Ready Registry Framework"
authors = [
    { name = "Queensland University of Technology - eResearch" },
    { name = "Murdoch University - Centre for Comparative Genomics" },
]
requires-python = ">=3.13"
dependencies = [
    "Django==5.2.1",
    "Pillow==11.3.0",
    "SQLAlchemy==1.3.24",
    "aws-xray-sdk==2.15.0",
    "awslambdaric==3.1.1",
    "boto3==1.40.41",
    "cachetools==4.1.1",
    "ccg-django-utils==0.4.2",
    "django-anymail==14.0",
    "django-cache-memoize==0.1.10",
    "django-countries==7.6.1",
    "django-csp==3.8",
    "django-extensions==3.2.3",
    "django-filter==25.1",
    "django-formtools==2.5.1",
    "django-otp==1.6.3",
    "django-registration-redux==2.13",
    "django-reversion==6.1.0",
    "django-simple-history==3.11.0",
    "django-storages==1.14.6",
    "django-stronghold==0.4.0",
    "django-two-factor-auth==1.18.0",
    "django-user-agents==0.4.0",
    "djangorestframework==3.16.0",
    "flatten_json==0.1.13",
    "gql-query-builder @ git+https://github.com/eresearchqut/gql-query-builder@a983448",
    "graphene-django==3.2.3",
    "jsonschema==4.4.0",
    "langcodes==3.3.0",
    "language_data==1.3",
    "lark==1.0.0",
    "openapi-client",
    "openpyxl==3.0.9",
    "phonenumberslite==8.12.39",
    "psycopg2-binary==2.9.10",
    "pycountry==24.6.1",
    "pypdftk==0.5",
    "python-dateutil==2.8.2",
    "python-magic==0.4.24",
    "pyyaml==6.0.3",
    "qrcode==6.1",
    "six==1.16.0",
    "ua-parser==0.10.0",
    "user-agents==2.2.0",
    "uwsgi==2.0.30",
]

[project.optional-dependencies]
dev = [
    "Werkzeug==3.1.5",
    "django-silk==4.4.0",
    "ipython",
    "python-Levenshtein",
    "ruff",
    "sphinx",
    "sphinxcontrib-fulltoc",
]
test = [
    "aloe==0.2.0",
    "aloe_django==0.2.0",
    "coverage==5.5",
    "django-nose==1.4.7",
    "nose-timer==0.7.5",
    "pynose==1.5.5",
    "pytest-django==4.5.2",
    "pytest==7.1.1",
    "pyvirtualdisplay==0.2.5",
    "requests==2.33.0",
    "selenium>=4.10.0",
    "sqlalchemy-utils==0.36.1",
    "stellar==0.4.5",
    "sure==1.4.11",
    "unittest-xml-reporting==3.2.0",
]

[tool.uv.sources]
openapi-client = { path = "./clients/xnat/generated" }

[tool.uv]
exclude-dependencies = ["nose"]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["rdrf", "registry", "report", "useraudit"]

[tool.ruff]
line-length = 80
exclude = [
    "**/migrations/[0-9][0-9][0-9][0-9]_*.py",
    "**/initial_data/*.py",
    "./build/**",
    "clients/*/generated/*",
    "rdrf/clients/*/generated/*",
]

[tool.ruff.lint]
extend-select = [
    "I",
    "B006"
]
exclude = [
    "**/tests/*.py",
]

[tool.ruff.format]
quote-style = "double"
