[tool.ruff]
line-length = 80
exclude = [
    "**/migrations/[0-9][0-9][0-9][0-9]_*.py",
    "**/initial_data/*.py",
    "./build/**",
    "clients/*/generated/*",
    "rdrf/clients/*/generated/*",
]

[tool.ruff.lint]
extend-select = [
    "I",
]
exclude = [
    "**/tests/*.py",
]

[tool.ruff.format]
quote-style = "double"