# Generated by Django 2.2.13 on 2020-11-25 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0056_patient_remove_clinician_fk'),
        ('rdrf', '0132_form_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='NofOneArm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.Patient')),
            ],
            options={
                'verbose_name': 'N-of-1 Arm',
                'verbose_name_plural': 'N-of-1 Arms',
            },
        ),
        migrations.CreateModel(
            name='NofOneCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='trials.NofOneArm')),
            ],
            options={
                'verbose_name': 'N-of-1 Cycle',
                'verbose_name_plural': 'N-of-1 Cycles',
            },
        ),
        migrations.CreateModel(
            name='NofOneTreatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('blinded_title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'N-of-1 Treatment',
                'verbose_name_plural': 'N-of-1 Treatments',
            },
        ),
        migrations.CreateModel(
            name='NofOneTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nofone_trials', to='rdrf.Registry')),
            ],
            options={
                'verbose_name': 'N-of-1 Trial',
                'verbose_name_plural': 'N-of-1 Trials',
            },
        ),
        migrations.CreateModel(
            name='NofOnePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='trials.NofOneCycle')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='trials.NofOneTreatment')),
            ],
            options={
                'verbose_name': 'N-of-1 Period',
                'verbose_name_plural': 'N-of-1 Periods',
            },
        ),
        migrations.AddField(
            model_name='nofonearm',
            name='trial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arms', to='trials.NofOneTrial'),
        ),
    ]
