Feature: Two-factor Authentication (2FA)
  As a user of TRRF
  I want the option to enable 2FA
  So that I have extra confidence in the security of my account and personal information.

  Background:
    Given export "ang.zip"
    Given a registry named "angelman" with code "ang"


  Scenario: Enable Two-factor auth
    Given  a user "Bob Smith" with username "bob.smith@user.com" and password "Test1!23"
    And I go to the "login" page
    And I login with username "bob.smith@user.com" and password "Test1!23"
    When I choose "Enable two-factor auth" from the "user" menu
    Then I should see "Follow the steps in this wizard to enable two-factor authentication."

    When I press the "Next" button
    Then I should see "To start using a token generator, please use your smartphone to scan the QR code below."
    And a "QR Code" image is displayed
    And a time based key is displayed

    When I enter my first generated OTP token
    Then I should see "Congratulations, you've successfully enabled two-factor authentication."

    # Login with 2FA
    When I reauthenticate with username "bob.smith@user.com" and password "Test1!23"
    Then I should see "Please enter the token generated by your token generator."

    When I enter my generated OTP token
    Then I am logged in successfully

    # Disable 2FA and login
    When I choose "Disable two-factor auth" from the "user" menu
    And I confirm to disable two-factor auth
    And I reauthenticate with username "bob.smith@user.com" and password "Test1!23"
    Then I am logged in successfully
