class RegistryFeatures:
    STAGES = "stages"
    FAMILY_LINKAGE = "family_linkage"
    CONSENT_CHECKS = "consent_checks"
    CONTEXTS = "contexts"
    CLINICIANS_HAVE_PATIENTS = "clinicians_have_patients"
    RULES_ENGINE = "rulesengine"
    NO_ADD_PATIENT_BUTTON = "no_add_patient_button"
    REGISTRATION = "registration"
    DOCTORS_LIST = "doctors_list"
    CLINICIAN_FORM = "clinician_form"
    PATIENT_TYPES = "patient_types"
    PATIENT_FORM_DOCTORS = "patient_form_doctors"
    PATIENT_GUID = "patient_guid"
    PATIENT_ADDRESS_IS_MANDATORY = "patient_address_is_mandatory"
    CLINICIAN_ETHICAL_CLEARANCE = "clinicians_need_ethical_clearance"
    CLINICIANS_SEE_CREATED_PATIENTS = "clinicians_see_created_patients"
    PATIENTS_CREATE_USERS = "patients_create_users"
    CONDITIONAL_RENDERING_DISABLED = "conditional_rendering_disabled"
    XNAT_INTEGRATION = "xnat_integration"
    LONGITUDINAL_FOLLOWUPS = "longitudinal_followups"
    USER_EMAIL_ACTIVATION_OPTIONAL_FOR_ADMIN = (
        "user_email_activation_optional_for_admin"
    )
    NO_TRANSLATION = "no_translation"
    FORMS_REQUIRE_TRANSLATION = "forms_require_translation"
    HIDE_UNTRANSLATED_FORMS = "hide_untranslated_forms"
