class RegistryFeatures:
    STAGES = "stages"
    FAMILY_LINKAGE = "family_linkage"
    VERIFICATION = "verification"
    QUESTIONNAIRES = "questionnaires"
    CONSENT_CHECKS = "consent_checks"
    PROMS_CLINICAL = "proms_clinical"
    CONTEXTS = "contexts"
    CLINICIANS_HAVE_PATIENTS = "clinicians_have_patients"
    RULES_ENGINE = "rulesengine"
    NO_ADD_PATIENT_BUTTON = "no_add_patient_button"
    REGISTRATION = "registration"
    DOCTORS_LIST = "doctors_list"
    CLINICIAN_FORM = "clinician_form"
    PATIENT_TYPES = "patient_types"
    PROMS_ADDING_DISABLED = "proms_adding_disabled"
    PATIENT_FORM_DOCTORS = "patient_form_doctors"
