# Generated by Django 2.1.9 on 2019-06-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_patients_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='rdrf_registry',
            field=models.ManyToManyField(related_name='patients', to='rdrf.Registry', verbose_name='Registry'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='working_groups',
            field=models.ManyToManyField(related_name='my_patients', to='groups.WorkingGroup', verbose_name='Working Group'),
        ),
    ]
