# Generated by Django 2.1.10 on 2019-07-08 15:30

from django.db import migrations
import registry.patients.models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0037_patient_label_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='form',
            field=registry.patients.models.ConsentFileField(blank=True, null=True, upload_to=registry.patients.models.upload_patient_consent_to, verbose_name='Consent form'),
        ),
    ]
