# Generated by Django 2.1.10 on 2019-07-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0038_patient_consent_upload_to_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatientrelative',
            name='location',
        ),
        migrations.RemoveField(
            model_name='patientrelative',
            name='location',
        ),
        migrations.AddField(
            model_name='historicalpatientrelative',
            name='country',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='historicalpatientrelative',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientrelative',
            name='country',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='patientrelative',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
