# Generated by Django 2.1.10 on 2019-09-13 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0040_signature_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStageRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('registered', 'Patient registered'), ('consented', 'Patient provided consent')], max_length=32, null=True)),
                ('from_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.PatientStage', null=True, blank=True)),
                ('to_stage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.PatientStage', null=True, blank=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='patientstagerule',
            unique_together={('from_stage', 'rule', 'to_stage')},
        ),
    ]
