# Generated by Django 2.1.10 on 2019-09-14 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0110_consent_section_and_question_timestamps'),
        ('patients', '0040_signature_encoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientStageRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('registered', 'Patient registered'), ('consented', 'Patient provided consent')], max_length=32, null=True)),
                ('order', models.PositiveIntegerField()),
                ('from_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.PatientStage')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rdrf.Registry')),
                ('to_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.PatientStage')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='patientstagerule',
            unique_together={('registry', 'from_stage', 'condition', 'to_stage')},
        ),
    ]
