# Generated by Django 2.1.10 on 2019-09-14 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0042_patient_stage_rule_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstagerule',
            name='from_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.PatientStage'),
        ),
        migrations.AlterField(
            model_name='patientstagerule',
            name='to_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='patients.PatientStage'),
        ),
    ]
