# Generated by Django 2.1.10 on 2019-10-15 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0111_commondataelement_widget_settings'),
        ('patients', '0047_patient_add_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientstage',
            name='registry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rdrf.Registry'),
        ),
    ]
