# Generated by Django 2.1.10 on 2019-10-15 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0049_patient_stage_registry_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientstage',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='rdrf.Registry'),
        ),
    ]
