# Generated by Django 2.2.9 on 2020-01-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0051_update_countries_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['family_name', 'given_names', 'date_of_birth'], 'permissions': (('can_see_full_name', 'Can see Full Name column'), ('can_see_dob', 'Can see Date of Birth column'), ('can_see_working_groups', 'Can see Working Groups column'), ('can_see_diagnosis_progress', 'Can see Diagnosis Progress column'), ('can_see_diagnosis_currency', 'Can see Diagnosis Currency column'), ('can_see_data_modules', 'Can see Data Modules column'), ('can_see_code_field', 'Can see Code Field column')), 'verbose_name_plural': 'Patient List'},
        ),
    ]
