# Generated by Django 2.2.13 on 2020-10-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0055_patient_registered_clinicians_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalpatient',
            name='clinician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='clinician',
        ),
    ]
