# Generated by Django 2.2.24 on 2021-07-23 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0056_patient_remove_clinician_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician address'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Clinician email'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician first name'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_hospital',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician hospital'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician last name'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician Name'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='clinician_phone_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Clinician phone number'),
        ),
        migrations.AlterField(
            model_name='clinicianother',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.Speciality', verbose_name='Clinician specialty'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician address'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Clinician email'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_first_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician first name'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_hospital',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician hospital'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_last_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician last name'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Clinician Name'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='clinician_phone_number',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Clinician phone number'),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='speciality',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='patients.Speciality', verbose_name='Clinician specialty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='registered_clinicians',
            field=models.ManyToManyField(blank=True, related_name='registered_patients', to=settings.AUTH_USER_MODEL, verbose_name='Registered clinicians'),
        ),
    ]
