# Generated by Django 2.2.25 on 2021-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0057_clinician_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnextofkinrelationship',
            name='relationship',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Relationship'),
        ),
        migrations.AlterField(
            model_name='nextofkinrelationship',
            name='relationship',
            field=models.CharField(max_length=100, unique=True, verbose_name='Relationship'),
        ),
    ]
