# Generated by Django 3.2.17 on 2023-03-28 14:39

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0153_add_longitudinal_followups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0059_living_status_column_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongitudinalFollowupEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_at', models.DateTimeField()),
                ('sent_at', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), default=list, size=None)),
                ('state', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent')], max_length=1)),
                ('created_by', models.ForeignKey(max_length=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('longitudinal_followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.longitudinalfollowup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name_plural': 'Longitudinal Followup Entries',
                'ordering': ('send_at',),
            },
        ),
        migrations.AddIndex(
            model_name='longitudinalfollowupentry',
            index=models.Index(condition=models.Q(('state', 'P')), fields=['state'], name='idx_pending'),
        ),
    ]
