# Generated by Django 3.2.19 on 2023-06-12 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0157_add_lanaguages'),
        ('patients', '0061_patientuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consentvalue',
            unique_together={('patient', 'consent_question')},
        ),
    ]
