# Generated by Django 3.2.23 on 2024-02-12 11:48

from django.db import migrations, models

def original_filename_defaults(apps, schema_editor):
    model_names = ['PatientConsent', 'HistoricalPatientConsent']
    for model_name in model_names:
        model = apps.get_model('patients', model_name)
        for consent in model.objects.all():
            consent.original_filename = consent.filename
            consent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0062_unique_consentvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpatientconsent',
            name='original_filename',
            field=models.CharField(null=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='original_filename',
            field=models.CharField(null=True, max_length=255),
        ),
        migrations.RunPython(
            original_filename_defaults, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='historicalpatientconsent',
            name='original_filename',
            field=models.CharField(null=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='original_filename',
            field=models.CharField(null=False, max_length=255),
        ),
    ]
