# Generated by Django 5.2.1 on 2026-01-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0066_patient_list_guid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaladdresstype',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical address type', 'verbose_name_plural': 'historical address types'},
        ),
        migrations.AlterModelOptions(
            name='historicalclinicianother',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical clinician other', 'verbose_name_plural': 'historical clinician others'},
        ),
        migrations.AlterModelOptions(
            name='historicalconsentvalue',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical consent value', 'verbose_name_plural': 'historical consent values'},
        ),
        migrations.AlterModelOptions(
            name='historicaldoctor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical doctor', 'verbose_name_plural': 'historical doctors'},
        ),
        migrations.AlterModelOptions(
            name='historicalnextofkinrelationship',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Next of Kin Relationship', 'verbose_name_plural': 'historical Next of Kin Relationships'},
        ),
        migrations.AlterModelOptions(
            name='historicalparentguardian',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical parent guardian', 'verbose_name_plural': 'historical parent guardians'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient', 'verbose_name_plural': 'historical Patient List'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatientaddress',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient address', 'verbose_name_plural': 'historical Patient Addresses'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatientconsent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient consent', 'verbose_name_plural': 'historical patient consents'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatientdoctor',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical medical professionals for patient', 'verbose_name_plural': 'historical medical professionals for patient'},
        ),
        migrations.AlterModelOptions(
            name='historicalpatientrelative',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical patient relative', 'verbose_name_plural': 'historical patient relatives'},
        ),
        migrations.AlterModelOptions(
            name='historicalspeciality',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical speciality', 'verbose_name_plural': 'historical specialitys'},
        ),
        migrations.AlterModelOptions(
            name='historicalstate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical state', 'verbose_name_plural': 'historical states'},
        ),
        migrations.AlterField(
            model_name='historicaladdresstype',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalclinicianother',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalconsentvalue',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalnextofkinrelationship',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalparentguardian',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatientaddress',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatientconsent',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatientdoctor',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalpatientrelative',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalspeciality',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalstate',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
