# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0082_auto_20181106_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='style',
            field=models.CharField(choices=[('N', 'Normal'), ('M', 'Matrix')], default='N', max_length=1),
        ),
    ]
