# Generated by Django 2.1.5 on 2019-06-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0095_auto_20190206_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailnotificationhistory',
            options={'verbose_name_plural': 'Email Notification History'},
        ),
    ]
