# Generated by Django 2.1.5 on 2019-05-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0096_verbose_name_fix_email_notification_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryform',
            name='conditional_rendering_rules',
            field=models.TextField(blank=True, help_text='Use the conditional rendering DSL to add rules.\n                     Click <a href="/forms/dsl-help" target="_blank">here</a> for more info', null=True),
        ),
    ]
