# Generated by Django 2.1.10 on 2019-08-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('rdrf', '0097_registryform_conditional_rendering_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicfields',
            name='is_section',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demographicfields',
            name='groups',
            field=models.ManyToManyField(related_name='groups', to='auth.Group'),
        ),
    ]
