# Generated by Django 2.1.10 on 2019-08-08 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0100_remove_demographicfields_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='demographicfields',
            unique_together={('registry', 'field')},
        ),
    ]
