# Generated by Django 2.1.10 on 2019-08-08 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0101_demographic_fields_unique_field_and_registry'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographicfields',
            name='status',
            field=models.IntegerField(choices=[(1, 'Read only'), (2, 'Hidden')], default=2),
        ),
    ]
