# Generated by Django 2.1.10 on 2019-08-08 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0103_demographic_fields_status_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographicfields',
            name='hidden',
        ),
        migrations.RemoveField(
            model_name='demographicfields',
            name='readonly',
        ),
    ]
