# Generated by Django 2.1.10 on 2019-08-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0104_demographic_fields_remove_hidden_and_readonly'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextformgroup',
            name='sort_order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
