# Generated by Django 2.1.10 on 2019-08-27 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0106_contextformgroup_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esignature', models.CharField(choices=[('enabled', 'enabled'), ('disabled', 'disabled'), ('required', 'required')], default='disabled', max_length=16)),
                ('consent_locked', models.BooleanField(default=False)),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent_configuration', to='rdrf.Registry')),
            ],
        ),
    ]
