# Generated by Django 2.1.10 on 2019-08-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0106_contextformgroup_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondataelement',
            name='widget_settings',
            field=models.TextField(blank=True, help_text='If the widget needs additional settings add them here'),
        ),
    ]
