# Generated by Django 2.1.10 on 2019-10-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0111_commondataelement_widget_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondataelement',
            name='datatype',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('calculated', 'Calculated'), ('date', 'Date'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('range', 'Range'), ('string', 'String'), ('time', 'Time')], default='string', help_text='type of field', max_length=50),
        ),
    ]
