# Generated by Django 2.1.10 on 2019-10-28 20:18

from django.db import migrations, models


def fix_cde_data_type(apps, schema_editor):
    CommonDataElement = apps.get_model('rdrf','CommonDataElement')
    CommonDataElement.objects.filter(datatype='String').update(datatype='string')
    CommonDataElement.objects.filter(datatype='Integer').update(datatype='integer')
    CommonDataElement.objects.filter(datatype='Range').update(datatype='range')
    CommonDataElement.objects.filter(datatype='Calculated').update(datatype='calculated')
    CommonDataElement.objects.filter(datatype='calculation').update(datatype='calculated')
    CommonDataElement.objects.filter(datatype='text').update(datatype='string')
    CommonDataElement.objects.filter(widget_name='TimeWidget').update(datatype='time')


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0112_cde_datatype_choices'),
    ]

    operations = [
        migrations.RunPython(
            fix_cde_data_type, migrations.RunPython.noop
        )
    ]
