# Generated by Django 2.1.10 on 2019-10-28 20:18

from django.db import migrations, models

from rdrf.models.data_fixes import CdeMappings


def fix_cde_data_type(cde_model):
    for k, v in CdeMappings.DATA_TYPE_MAPPING.items():
        cde_model.objects.filter(datatype__iexact=k.lower()).update(datatype=v)
    cde_model.objects.filter(widget_name__iexact='timewidget').update(datatype='time')


def fix_cde_widget_name(cde_model):
    for k, v in CdeMappings.DATA_TYPE_MAPPING.items():
        cde_model.objects.filter(widget_name__iexact=k.lower()).update(widget_name=v)


def fix_data(apps, schema_editor):
    CommonDataElement = apps.get_model('rdrf','CommonDataElement')
    fix_cde_data_type(CommonDataElement)
    fix_cde_widget_name(CommonDataElement)

class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0112_cde_datatype_choices'),
    ]

    operations = [
        migrations.RunPython(
            fix_data, migrations.RunPython.noop
        )
    ]
