# Generated by Django 2.1.12 on 2019-11-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('rdrf', '0114_registry_forms_add_default_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_name', models.CharField(choices=[('Demographics', 'Demographics'), ('Consents', 'Consents'), ('Clinician', 'Clinician'), ('Proms', 'Proms'), ('Family linkage', 'Family linkage')], max_length=50)),
                ('custom_name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='formtitle',
            unique_together={('registry', 'group', 'default_name', 'order')},
        ),
    ]
