# Generated by Django 2.1.12 on 2019-11-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0118_clinical_data_created_updated_ts'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondataelement',
            name='randomize',
            field=models.BooleanField(default=False, help_text='Randomize permitted value group value is this CDE has a PVG set'),
        ),
    ]
