# Generated by Django 2.2.10 on 2020-02-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0119_remove_ip_restrict_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commondataelement',
            name='datatype',
            field=models.CharField(choices=[('boolean', 'Boolean'), ('calculated', 'Calculated'), ('date', 'Date'), ('file', 'File'), ('float', 'Float'), ('integer', 'Integer'), ('range', 'Range'), ('string', 'String'), ('time', 'Time'), ('duration', 'Duration')], default='string', help_text='type of field', max_length=50),
        ),
    ]
