# Generated by Django 2.2.9 on 2020-02-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0119_remove_ip_restrict_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdrfcontext',
            name='context_form_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.ContextFormGroup'),
        ),
    ]
