# Generated by Django 2.2.9 on 2020-01-23 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0120_commondataelement_abnormality_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='context_form_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.ContextFormGroup'),
        ),
        migrations.AddField(
            model_name='survey',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.RegistryForm'),
        ),
    ]
