# Generated by Django 2.2.9 on 2020-02-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0120_email_notifications_update_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='default_for_notification',
            field=models.CharField(choices=[('account-locked', 'Account Locked'), ('other-clinician', 'Other Clinician'), ('new-patient', 'New Patient Registered'), ('new-patient-parent', 'New Patient Registered (Parent)'), ('account-verified', 'Account Verified'), ('password-expiry-warning', 'Password Expiry Warning'), ('reminder', 'Reminder'), ('clinician-signup-request', 'Clinician Signup Request'), ('clinician-activation', 'Clinician Activation'), ('clinician-selected', 'Clinician Selected'), ('participant-clinician-notification', 'Participant Clinician Notification'), ('patient-consent-change', 'Patient Consent Change')], default=None, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='emailtemplate',
            unique_together={('language', 'default_for_notification')},
        ),
    ]
