# Generated by Django 2.2.9 on 2020-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0121_cde_add_email_datatype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='email_from',
            field=models.EmailField(default='no-reply@trrf.registryframework.net', max_length=254),
        ),
    ]
