# Generated by Django 2.2.9 on 2020-02-02 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rdrf', '0122_review_and_verification_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicaldata',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='cde_path',
            field=models.CharField(blank=True, help_text='Format: <i>/[form_name]/[section_code]/</i><br/>Example: <i>/BaselineTreatmentForm/BASELINETREATMENT/</i>', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(choices=[('account-locked', 'Account Locked'), ('other-clinician', 'Other Clinician'), ('new-patient', 'New Patient Registered'), ('new-patient-parent', 'New Patient Registered (Parent)'), ('account-verified', 'Account Verified'), ('password-expiry-warning', 'Password Expiry Warning'), ('reminder', 'Reminder'), ('clinician-signup-request', 'Clinician Signup Request'), ('clinician-activation', 'Clinician Activation'), ('clinician-selected', 'Clinician Selected'), ('participant-clinician-notification', 'Participant Clinician Notification'), ('patient-consent-change', 'Patient Consent Change'), ('survey-request', 'Survey Request')], max_length=100),
        ),
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('action_type', models.CharField(choices=[('PR', 'Patient Report')], max_length=2)),
                ('data', models.TextField(null=True)),
                ('groups_allowed', models.ManyToManyField(blank=True, to='auth.Group')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
    ]
