# Generated by Django 2.2.10 on 2020-03-27 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0053_patient_carer_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdrf', '0123_email_notification_email_from_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdefile',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='cdefile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
