# Generated by Django 2.2.10 on 2020-04-10 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0125_cde_file_user_and_patient_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileTypeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Archive', 'Archive'), ('Audio', 'Audio'), ('Document', 'Document'), ('Image', 'Image'), ('Spreadsheet', 'Spreadsheet'), ('Other', 'Other'), ('Presentation', 'Presentation'), ('Text', 'Text'), ('Video', 'Video')], max_length=32, unique=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=16)),
                ('mime_type', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('enabled', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.UploadFileTypeCategory')),
            ],
        ),
        migrations.AddField(
            model_name='consentconfiguration',
            name='allowed_file_types',
            field=models.ManyToManyField(related_name='_consentconfiguration_allowed_file_types_+', to='rdrf.UploadFileType'),
        ),
    ]
