# Generated by Django 2.2.10 on 2020-05-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0126_blacklistedmimetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdefile',
            name='mime_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
