# Generated by Django 2.2.10 on 2020-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0126_upload_file_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedMimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
    ]
