# Generated by Django 2.2.13 on 2020-06-08 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import rdrf.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0053_patient_carer_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('rdrf', '0128_cdefile_set_mime_type_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=rdrf.helpers.utils.generate_token, max_length=80, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(default='C', max_length=1)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.RDRFContext')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ParentGuardian')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(default='C', max_length=1)),
                ('has_changed', models.CharField(blank=True, max_length=1, null=True)),
                ('current_status', models.CharField(blank=True, max_length=1, null=True)),
                ('verification_status', models.CharField(blank=True, max_length=1, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('patient_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rdrf.PatientReview')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=80)),
                ('review_type', models.CharField(choices=[('R', 'Caregiver Review'), ('V', 'Clinician Verification')], default='R', max_length=1)),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='rdrf.Registry')),
            ],
        ),
        migrations.AddField(
            model_name='clinicaldata',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commondataelement',
            name='abnormality_condition',
            field=models.TextField(blank=True, help_text='Rules triggering a visual notification encouraging the user to process with further investigations', null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='context_form_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.ContextFormGroup'),
        ),
        migrations.AddField(
            model_name='survey',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rdrf.RegistryForm'),
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='cde_path',
            field=models.CharField(blank=True, help_text='Format: <i>/[form_name]/[section_code]/</i><br/>Example: <i>/BaselineTreatmentForm/BASELINETREATMENT/</i>', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='max_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='commondataelement',
            name='min_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Only used for numeric fields', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(choices=[('account-locked', 'Account Locked'), ('other-clinician', 'Other Clinician'), ('new-patient', 'New Patient Registered'), ('new-patient-parent', 'New Patient Registered (Parent)'), ('account-verified', 'Account Verified'), ('password-expiry-warning', 'Password Expiry Warning'), ('reminder', 'Reminder'), ('clinician-signup-request', 'Clinician Signup Request'), ('clinician-activation', 'Clinician Activation'), ('clinician-selected', 'Clinician Selected'), ('participant-clinician-notification', 'Participant Clinician Notification'), ('patient-consent-change', 'Patient Consent Change'), ('new-carer', 'Primary Caregiver Registered'), ('carer-invited', 'Primary Caregiver Invited'), ('carer-assigned', 'Primary Caregiver Assigned'), ('carer-activated', 'Primary Caregiver Activated'), ('carer-deactivated', 'Primary Caregiver Deactivated'), ('survey-request', 'Survey Request')], max_length=100),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(blank=True, max_length=80, null=True)),
                ('section_code', models.CharField(blank=True, max_length=80, null=True)),
                ('cde_code', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('V', 'Verified'), ('N', 'Not Verified'), ('U', 'Unknown')], max_length=1, null=True)),
                ('username', models.CharField(blank=True, max_length=80, null=True)),
                ('data', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.RDRFContext')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.Patient')),
                ('patient_review_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.PatientReviewItem')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('appearance_condition', models.TextField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('item_type', models.CharField(choices=[('CF', 'Consent Item'), ('DF', 'Demographics Field'), ('CA', 'Clinician Access'), ('MT', 'Multi Target'), ('SC', 'Section Monitor'), ('MI', 'Add to Section'), ('MU', 'Update Section'), ('V', 'Verification Section')], max_length=2)),
                ('category', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('fields', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('target_code', models.CharField(blank=True, max_length=80, null=True)),
                ('target_metadata', models.TextField(blank=True, null=True)),
                ('form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.RegistryForm')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rdrf.Review')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.Section')),
            ],
        ),
        migrations.AddField(
            model_name='patientreviewitem',
            name='review_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.ReviewItem'),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Review'),
        ),
        migrations.AddField(
            model_name='patientreview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('action_type', models.CharField(choices=[('PR', 'Patient Report'), ('SR', 'Patient Status Report')], max_length=2)),
                ('data', models.TextField(null=True)),
                ('scope', models.CharField(choices=[('U', 'Universal'), ('P', 'Patient')], max_length=1)),
                ('groups_allowed', models.ManyToManyField(blank=True, to='auth.Group')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
    ]
