# Generated by Django 2.2.10 on 2020-04-27 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rdrf', '0128_cdefile_set_mime_type_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCookie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.TextField()),
                ('max_age', models.PositiveIntegerField()),
                ('expires', models.DateTimeField()),
                ('locked_out', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
