# Generated by Django 2.2.10 on 2020-05-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0129_devicecookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecookie',
            name='lock_out_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
