# Generated by Django 2.2.13 on 2020-10-14 10:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0131_clinician_assignment_event_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryform',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
