# Generated by Django 2.2.24 on 2021-11-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rdrf', '0132_form_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryform',
            name='groups_readonly',
            field=models.ManyToManyField(blank=True, related_name='groups_readonly', to='auth.Group'),
        ),
    ]
