# Generated by Django 2.2.24 on 2022-01-19 14:02

from django.db import migrations, models

def set_cfg_code(apps, schema_editor):
    ContextFormGroup = apps.get_model('rdrf', 'ContextFormGroup')
    cfgs = ContextFormGroup.objects.all()
    for idx, cfg in enumerate(cfgs):
        cfg.code = f'CFG-{(idx+1)}'
        cfg.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0134_add_lookup_cde_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextformgroup',
            name='code',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(
            set_cfg_code,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='contextformgroup',
            name='code',
            field=models.CharField(max_length=30, unique=True),
        )
    ]
