# Generated by Django 2.2.27 on 2022-03-17 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0138_file_uploaded_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('ar', 'العربية'), ('es', 'Español'), ('de', 'Deutsch'), ('fr', 'Français'), ('he', 'עִבְרִית'), ('it', 'Italiano'), ('pl', 'Język polski'), ('pt', 'Português'), ('zh-CN', '汉语'), ('zh-TW', '漢語')], max_length=6),
        ),
    ]
