# Generated by Django 2.2.27 on 2022-04-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0140_add_abbreviated_name_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='context_form_group',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='form',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='registry',
        ),
        migrations.RemoveField(
            model_name='surveyassignment',
            name='registry',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='cde',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='precondition',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='surveyrequest',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='surveyrequest',
            name='registry',
        ),
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(choices=[('account-locked', 'Account Locked'), ('other-clinician', 'Other Clinician'), ('new-patient-user-registered', 'User associated with patient was created by registering ["registration" feature required]'), ('new-patient-parent', 'New Patient Registered (Parent)'), ('new-patient-user-added', 'User associated with patient was created on the "Add Patient Page" ["patients_create_users" feature required]'), ('account-verified', 'Account Verified'), ('password-expiry-warning', 'Password Expiry Warning'), ('reminder', 'Reminder'), ('clinician-signup-request', 'Clinician Signup Request'), ('clinician-activation', 'Clinician Activation'), ('clinician-selected', 'Clinician Selected'), ('participant-clinician-notification', 'Participant Clinician Notification'), ('patient-consent-change', 'Patient Consent Change'), ('new-carer', 'Primary Caregiver Registered'), ('carer-invited', 'Primary Caregiver Invited'), ('carer-assigned', 'Primary Caregiver Assigned'), ('carer-activated', 'Primary Caregiver Activated'), ('carer-deactivated', 'Primary Caregiver Deactivated'), ('duplicate-patient-set', 'Duplicate Patient Set'), ('clinician-assigned', 'Clinician Assigned'), ('clinician-unassigned', 'Clinician Unassigned'), ('file-uploaded', 'File Uploaded')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formtitle',
            name='default_title',
            field=models.CharField(choices=[('Demographics', 'Demographics'), ('Consents', 'Consents'), ('Clinician', 'Clinician'), ('Family linkage', 'Family Linkage')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Precondition',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveyAssignment',
        ),
        migrations.DeleteModel(
            name='SurveyQuestion',
        ),
        migrations.DeleteModel(
            name='SurveyRequest',
        ),
    ]
