# Generated by Django 2.2.27 on 2022-05-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0141_remove_proms'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rdrfcontext',
            constraint=models.UniqueConstraint(fields=('registry', 'content_type', 'object_id', 'context_form_group'), name='unique_patient_context'),
        ),
    ]
