# Generated by Django 2.2.28 on 2022-07-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0141_remove_proms'),
    ]

    operations = [
        migrations.AddField(
            model_name='registryform',
            name='save_position',
            field=models.BooleanField(default=False, help_text='Return to the current position on form save'),
        ),
    ]
