# Generated by Django 2.2.28 on 2022-08-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0142_save_form_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryDashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
        ),
        migrations.CreateModel(
            name='RegistryDashboardWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('demographics', 'Demographics'), ('clinical_data', 'Clinical Data'), ('consents', 'Consent'), ('module_progress', 'Module Progress')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('free_text', models.CharField(blank=True, max_length=255)),
                ('registry_dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='rdrf.RegistryDashboard')),
            ],
            options={
                'unique_together': {('registry_dashboard', 'widget_type')},
            },
        ),
        migrations.CreateModel(
            name='RegistryDashboardFormLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('cfg_code', models.CharField(max_length=30)),
                ('form_name', models.CharField(max_length=80)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='rdrf.RegistryDashboardWidget')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RegistryDashboardCDEData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('cfg_code', models.CharField(max_length=30)),
                ('form_name', models.CharField(max_length=80)),
                ('section_code', models.CharField(max_length=100)),
                ('cde_code', models.CharField(max_length=30)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdes', to='rdrf.RegistryDashboardWidget')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
