# Generated by Django 2.2.28 on 2022-08-17 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0143_registrydashboard_registrydashboardcdedata_registrydashboardformlink_registrydashboardwidget'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryDashboardDemographicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('patient_demographic_field', models.CharField(max_length=255)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demographics', to='rdrf.RegistryDashboardWidget')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
