# Generated by Django 3.2.15 on 2022-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0144_registry_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='splash_screen',
            field=models.TextField(blank=True),
        ),
    ]
