# Generated by Django 3.2.15 on 2022-10-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0147_section_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='commondataelement',
            name='calculation_query',
            field=models.TextField(blank=True, help_text='GraphQL Query to obtain patient information for use in CDE calculation'),
        ),
    ]
