# Generated by Django 3.2.15 on 2022-11-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0148_add_cde_calculation_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registryform',
            name='applicability_condition',
            field=models.TextField(blank=True, help_text="e.g. patient.country_of_birth == 'AU'<br /><em>Note, this only applies to forms within Fixed Context Form Groups</em>", null=True),
        ),
    ]
