# Generated by Django 3.2.17 on 2023-03-28 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0152_email_preferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='description',
            field=models.CharField(choices=[('account-locked', 'Account Locked'), ('other-clinician', 'Other Clinician'), ('new-patient-user-registered', 'User associated with patient was created by registering ["registration" feature required]'), ('new-patient-parent', 'New Patient Registered (Parent)'), ('new-patient-user-added', 'User associated with patient was created on the "Add Patient Page" ["patients_create_users" feature required]'), ('account-verified', 'Account Verified'), ('password-expiry-warning', 'Password Expiry Warning'), ('reminder', 'Reminder'), ('clinician-signup-request', 'Clinician Signup Request'), ('clinician-activation', 'Clinician Activation'), ('clinician-selected', 'Clinician Selected'), ('participant-clinician-notification', 'Participant Clinician Notification'), ('patient-consent-change', 'Patient Consent Change'), ('new-carer', 'Primary Caregiver Registered'), ('carer-invited', 'Primary Caregiver Invited'), ('carer-assigned', 'Primary Caregiver Assigned'), ('carer-activated', 'Primary Caregiver Activated'), ('carer-deactivated', 'Primary Caregiver Deactivated'), ('duplicate-patient-set', 'Duplicate Patient Set'), ('clinician-assigned', 'Clinician Assigned'), ('clinician-unassigned', 'Clinician Unassigned'), ('file-uploaded', 'File Uploaded'), ('longitudinal-followup', 'Longitudinal Followup')], max_length=100),
        ),
        migrations.CreateModel(
            name='LongitudinalFollowup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the followup as displayed to the user', max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('frequency', models.DurationField(help_text='The frequency at which followups are sent (days HH:MM:SS)')),
                ('debounce', models.DurationField(help_text='The range in which subsequent followups are de-duplicated (days HH:MM:SS)', null=True)),
                ('condition', models.TextField(blank=True)),
                ('context_form_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rdrf.contextformgroup')),
            ],
        ),
    ]
