# Generated by Django 3.2.19 on 2023-07-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0159_whitelistedfileextension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedMimeType',
        ),
    ]
