# Generated by Django 3.2.19 on 2023-06-26 10:28

from django.db import migrations

def remove_zips(apps, schema_editor):
    WhitelistedFileExtension = apps.get_model('rdrf', 'WhitelistedFileExtension')
    WhitelistedFileExtension.objects.filter(file_extension__in=['.zip', '.gz']).delete()


def rollback_remove_zips(apps, schema_editor):
    WhitelistedFileExtension = apps.get_model('rdrf', 'WhitelistedFileExtension')
    WhitelistedFileExtension.objects.bulk_create([
        WhitelistedFileExtension(file_extension='.zip'),
        WhitelistedFileExtension(file_extension='.gz')])


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0162_rename_email_activation_feature'),
    ]

    operations = [
        migrations.RunPython(remove_zips, rollback_remove_zips)
    ]
