# Generated by Django 3.2.19 on 2023-07-26 11:10

from django.db import migrations, models
import rdrf.helpers.utils


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0163_update_default_whitelistedfileextentions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistedfileextension',
            name='file_extension',
            field=models.CharField(max_length=256, unique=True, validators=[rdrf.helpers.utils.validate_file_extension_format]),
        ),
    ]
