# Generated by Django 3.2.23 on 2024-02-07 14:08

from django.db import migrations, models


def original_filename_defaults(apps, schema_editor):
    CDEFile = apps.get_model('rdrf', 'CDEFile')
    for cde_file in CDEFile.objects.all():
        cde_file.original_filename = cde_file.filename
        cde_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0167_brazilian_portuguese'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdefile',
            name='original_filename',
            field=models.CharField(null=True, max_length=255),
        ),
        migrations.RunPython(
            original_filename_defaults, migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='cdefile',
            name='original_filename',
            field=models.CharField(max_length=255),
        ),
    ]
