# Generated by Django 4.2.14 on 2024-08-16 11:19
from django.conf import settings
from django.db import migrations, models


def insert_languages(apps, schema_editor):
    Language = apps.get_model('rdrf', 'Language')
    for language in settings.LANGUAGES_ASSOC_LIST:
        print(f"Adding language: {language}")
        Language.objects.create(language_code=language)


class Migration(migrations.Migration):

    dependencies = [
        ('rdrf', '0171_bulgarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('af', 'Afrikaans'), ('ar-AR', 'العربية'), ('bg', 'български език'), ('cs', 'Čeština'), ('de', 'Deutsch'), ('es', 'Español'), ('el', 'Ελληνικά'), ('fr', 'Français'), ('he', 'עִבְרִית'), ('hi', 'हिन्दी'), ('hu', 'Magyar'), ('id', 'Bahasa Indonesia'), ('it', 'Italiano'), ('ms', 'Bahasa Melayu'), ('pl', 'Język polski'), ('pt', 'Português'), ('pt-BR', 'Português (Brasil)'), ('ro', 'Română'), ('ru', 'русский язык'), ('sv', 'Svenska'), ('tr', 'Türkçe'), ('ur', 'اردو'), ('vi', 'Tiếng Việt'), ('zh-CN', '简体中文'), ('zh-TW', '繁體中文')], max_length=6, unique=True)),
            ],
            options={'ordering': ('language_code',)},
        ),
        migrations.RunPython(
            insert_languages, migrations.RunPython.noop
        ),
        migrations.CreateModel(
            name='RegistryFormTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.OneToOneField(on_delete=models.deletion.CASCADE, to='rdrf.language')),
                ('translated_forms', models.ManyToManyField(blank=True, to='rdrf.registryform', help_text="Select which forms have been completely translated for the selected language.")),
            ],
        ),
    ]
