# Generated by Django 3.2.15 on 2022-12-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalDataView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('form_name', models.CharField(max_length=80)),
                ('form_entry_num', models.IntegerField()),
                ('section_code', models.CharField(max_length=100)),
                ('cde_entry_num', models.IntegerField()),
                ('cde_code', models.CharField(max_length=30)),
                ('cde_value', models.TextField()),
            ],
            options={
                'db_table': 'analytics_clinicaldataview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClinicalDataViewRefreshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
            ],
        ),

    ]

