from django.conf import settings


def production(request):
    return {'production': settings.PRODUCTION}


def common_settings(request):
    return {
        'ACCOUNT_SELF_UNLOCK_ENABLED': settings.ACCOUNT_SELF_UNLOCK_ENABLED,
        'HIGHLIGHT_FORM_CHANGES_ENABLED': settings.HIGHLIGHT_FORM_CHANGES_ENABLED,
        'ENABLE_CROWDIN_IN_CONTEXT_TRANSLATION': settings.ENABLE_CROWDIN_IN_CONTEXT_TRANSLATION,
        'CROWDIN_IN_CONTEXT_PROJECT_ID': settings.CROWDIN_IN_CONTEXT_PROJECT_ID,
        'CROWDIN_IN_CONTEXT_DOMAIN': settings.CROWDIN_IN_CONTEXT_DOMAIN,
        'ENABLE_VIDEO_HOSTING': settings.ENABLE_VIDEO_HOSTING,
        'AUTO_LOGOUT_ENABLED': settings.AUTO_LOGOUT_ENABLED,
        'AUTO_LOGOUT_WARN_AFTER_MS': settings.AUTO_LOGOUT_WARN_AFTER_MS,
        'AUTO_LOGOUT_WARNED_USER_AFTER_MS': settings.AUTO_LOGOUT_WARNED_USER_AFTER_MS,
    }
