# Generated by Django 2.2.24 on 2021-12-03 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('rdrf', '0133_registryform_groups_readonly'),
        ('groups', '0017_staff_help_text'),
        ('explorer', '0010_fieldvalue_raw_boolean'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('compiled_query', models.TextField(null=True)),
                ('access_groups', models.ManyToManyField(blank=True, to='auth.Group')),
                ('filter_consents', models.ManyToManyField(blank=True, to='rdrf.ConsentQuestion')),
                ('filter_working_groups', models.ManyToManyField(blank=True, related_name='filter_working_groups', to='groups.WorkingGroup')),
                ('registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rdrf.Registry')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DemographicField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('report_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.ReportDesign')),
            ],
        ),
        migrations.CreateModel(
            name='CdeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=255)),
                ('report_design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='explorer.ReportDesign')),
            ],
        ),
    ]
