# Generated by Django 3.2.15 on 2022-12-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_alter_fieldvalue_raw_boolean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='access_group',
        ),
        migrations.RemoveField(
            model_name='query',
            name='registry',
        ),
        migrations.DeleteModel(
            name='FieldValue',
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
